### ISSUE TITLE
DTM2ASCII

### ISSUE THREAD

**Issue by jhpoosthoek** [qgis/QGIS-Processing#49]
I upgraded to the latest processing version and get the error: No module named DTM2ASCII

I use QGIS Lyon on Win7 x64

**Comment by gioman** [comment]
Hi, not the right place where to report issues (use the qgis bug tracker). Anyway it seems that something has been changed recently in the lidar tools in processing https://github.com/qgis/QGIS/pull/2464 you get the error with or without the code changed in this commit?

**Comment by jhpoosthoek** [comment]
Hey, after updating QGIS processing all works again. Were you behind that? ;-)

Ok, next time I'll use the qgis bug tracker
